package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Client;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    Client selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    List<Client> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    int updateByPrimaryKey(Client record);
}