package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Service;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SERVICE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SERVICE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    int insert(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SERVICE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    Service selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SERVICE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    List<Service> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SERVICE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    int updateByPrimaryKey(Service record);
}