package lt.vu.mybatis.model;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.LICENCE_PLATE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private String licencePlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MAKE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private String make;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MODEL
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.YEAR
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.OWNER_ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private Integer ownerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.LICENCE_PLATE
     *
     * @return the value of PUBLIC.CAR.LICENCE_PLATE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public String getLicencePlate() {
        return licencePlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.LICENCE_PLATE
     *
     * @param licencePlate the value for PUBLIC.CAR.LICENCE_PLATE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setLicencePlate(String licencePlate) {
        this.licencePlate = licencePlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MAKE
     *
     * @return the value of PUBLIC.CAR.MAKE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public String getMake() {
        return make;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MAKE
     *
     * @param make the value for PUBLIC.CAR.MAKE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setMake(String make) {
        this.make = make;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MODEL
     *
     * @return the value of PUBLIC.CAR.MODEL
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MODEL
     *
     * @param model the value for PUBLIC.CAR.MODEL
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.YEAR
     *
     * @return the value of PUBLIC.CAR.YEAR
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.YEAR
     *
     * @param year the value for PUBLIC.CAR.YEAR
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.OWNER_ID
     *
     * @return the value of PUBLIC.CAR.OWNER_ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.OWNER_ID
     *
     * @param ownerId the value for PUBLIC.CAR.OWNER_ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }
}