package lt.vu.mybatis.model;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.CARMAKE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private String carmake;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.MECHANIC_ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private Integer mechanicId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.ID
     *
     * @return the value of PUBLIC.CLIENT.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.ID
     *
     * @param id the value for PUBLIC.CLIENT.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.CARMAKE
     *
     * @return the value of PUBLIC.CLIENT.CARMAKE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public String getCarmake() {
        return carmake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.CARMAKE
     *
     * @param carmake the value for PUBLIC.CLIENT.CARMAKE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setCarmake(String carmake) {
        this.carmake = carmake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.NAME
     *
     * @return the value of PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.NAME
     *
     * @param name the value for PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.MECHANIC_ID
     *
     * @return the value of PUBLIC.CLIENT.MECHANIC_ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public Integer getMechanicId() {
        return mechanicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.MECHANIC_ID
     *
     * @param mechanicId the value for PUBLIC.CLIENT.MECHANIC_ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setMechanicId(Integer mechanicId) {
        this.mechanicId = mechanicId;
    }
}