package lt.vu.mybatis.model;

public class Mechanic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MECHANIC.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MECHANIC.NAME
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MECHANIC.ROLE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MECHANIC.ID
     *
     * @return the value of PUBLIC.MECHANIC.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MECHANIC.ID
     *
     * @param id the value for PUBLIC.MECHANIC.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MECHANIC.NAME
     *
     * @return the value of PUBLIC.MECHANIC.NAME
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MECHANIC.NAME
     *
     * @param name the value for PUBLIC.MECHANIC.NAME
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MECHANIC.ROLE
     *
     * @return the value of PUBLIC.MECHANIC.ROLE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MECHANIC.ROLE
     *
     * @param role the value for PUBLIC.MECHANIC.ROLE
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setRole(String role) {
        this.role = role;
    }
}