package lt.vu.mybatis.model;

public class Service {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SERVICE.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SERVICE.ADDRESS
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SERVICE.NAME
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SERVICE.ID
     *
     * @return the value of PUBLIC.SERVICE.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SERVICE.ID
     *
     * @param id the value for PUBLIC.SERVICE.ID
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SERVICE.ADDRESS
     *
     * @return the value of PUBLIC.SERVICE.ADDRESS
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SERVICE.ADDRESS
     *
     * @param address the value for PUBLIC.SERVICE.ADDRESS
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SERVICE.NAME
     *
     * @return the value of PUBLIC.SERVICE.NAME
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SERVICE.NAME
     *
     * @param name the value for PUBLIC.SERVICE.NAME
     *
     * @mbg.generated Sun Apr 24 21:00:52 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}